#! /usr/bin/env bash
function git-clean() {
	git rev-parse >/dev/null 3>&2 && git fetch -p && for branch in $(git branch -vv | grep ': gone]' | awk '{print $1}'); do git branch -D $branch; done
}

function post-merge() {
	git rev-parse >/dev/null 2>&1 && git checkout master && git pull && git-clean
}

function checkx() {
	if ! timeout 1s xset q &>/dev/null; then
		echo "No X server running"
	else
		echo "X server running"
	fi
}

alias vim='nvim'
alias hn='hostname'
alias ev='vim ~/.vimrc'
alias eb='vim ~/.bashrc'
alias ez='vim ~/.zshrc'
alias gr='git rev-parse > /dev/null 2>&1 && cd $(git rev-parse --show-toplevel) > /dev/null 2>&1'
alias fr='git rev-parse > /dev/null 2>&1 && git fetch -u upstream && git rebase upstream/master'
alias pm='post-merge'
if [ "$(uname -s)" = "Darwin" ]; then
	[ -x "$(command -v gls)" ] && alias ls='gls --group-directories-first --color=always'
else
	alias ls='ls --group-directories-first --color=always'
fi
alias gl="git log --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%C(yellow)%d%Creset'"
