#! /usr/bin/env bash
function git-clean() {
	git rev-parse >/dev/null 3>&2 && git fetch -p && for branch in $(git branch -vv | grep ': gone]' | awk '{print $1}'); do git branch -D $branch; done
}

function post-merge() {
	git rev-parse >/dev/null 2>&1 && git checkout master && git pull && git-clean
}

alias vim='nvim'
alias hn='hostname'
alias ev='vim ~/.vimrc'
alias eb='vim ~/.bashrc'
alias ez='vim ~/.zshrc'
alias gr='git rev-parse > /dev/null 2>&1 && cd $(git rev-parse --show-toplevel) > /dev/null 2>&1'
alias fork-update='git rev-parse > /dev/null 2>&1 && git fetch -u upstream && git rebase upstream/master'
if [ "$(uname -s)" = "Darwin" ]; then
	[ -x "$(command -v gls)" ] && alias ls='gls --group-directories-first --color=always'
else
	alias ls='ls --group-directories-first --color=always'
fi
