return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "diff",
        "dockerfile",
        "go",
        "gomod",
        "gosum",
        "helm",
        "html",
        "ini",
        "javascript",
        "json",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "proto",
        "python",
        "regex",
        "rego",
        "ruby",
        "sql",
        "terraform",
        "tsx",
        "typescript",
        "vim",
        "xml",
        "yaml",
      },
      sync_install = false,
      highlight = {
        enable = true,
      },
    },
  },
}
